#服务器端口
server:
  port: 9100

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

# mybatis
mybatis-plus:
  mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
  # 实体扫描
  type-aliases-package: org.springblade.**.entity
  global-config:
    db-config:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

