#服务器端口
server:
  port: 9102

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.test.url}
    username: ${blade.datasource.test.username}
    password: ${blade.datasource.test.password}

  # mybatis
  #mybatis-plus:
  #mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
  # 实体扫描
  #type-aliases-package: org.springblade.**.entity
