#服务器端口
server:
  port: 9101

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.prod.url}
    username: ${blade.datasource.prod.username}
    password: ${blade.datasource.prod.password}



  # mybatis
  #mybatis-plus:
  #mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
  # 实体扫描
  #type-aliases-package: org.springblade.**.entity
